### ISSUE TITLE
Sqoop gives error with the generated password

### ISSUE THREAD

**Issue by purval** [scm-spain/chamberlain#1]
I have used this utility and it generates an encrypted password for me.
When I use it in sqoop command it complains with 
**Caused by: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher** error.

I am using Sqoop 1.4.6
arguments provided -password.pwd -p password -h passPhrAse -s SALT

Can you help?

Regards,
Purval

**Comment by vcapelca** [comment]
Hi there Purval,

Thanks for attempting to use our tool. We had this type of error some time, and as far as I remember we were forgetting to provide Sqoop with the correct parameters. I'm not sure if it's your case aswell, but could you check if you are providing Sqoop with the passphrase and salt you chose for your password encryption? We specify it like this when using sqoop-action from Oozie (if using Sqoop, just remove the "arg" strings):
`<arg>-D</arg>        <arg>org.apache.sqoop.credentials.loader.class=org.apache.sqoop.util.password.CryptoFileLoader</arg>
        <arg>-D</arg>
        <arg>org.apache.sqoop.credentials.loader.crypto.passphrase=${passwordPassphrase}</arg>
        <arg>-D</arg>
        <arg>org.apache.sqoop.credentials.loader.crypto.salt=${passwordSalt}</arg>`

Tell us if this works :)

**Comment by purval** [comment]
Awesome. I was running the code from intellij and I just copy pasted the encrypted string from the console to a file. It didn't work.
Then I followed the steps mentioned in readme of this project and used that .txt file. It worked.

Thanks,
Purval
